CREATE TABLE ACCOUNTS
(
  ACCOUNT_ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_6BF6500B_EC7C_4E0F_BBFE_D4345B5C5799) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  CLIENT_ID INTEGER NOT NULL,
  DEPOSIT DOUBLE NOT NULL,
  ACCOUNT_TYPE INTEGER,
  OVERDRAFT INTEGER,
  CONSTRAINT CONSTRAINT_AF FOREIGN KEY (ACCOUNT_TYPE) REFERENCES ACCOUNT_TYPES (ACCOUNT_TYPE_ID)
);
CREATE TABLE ACCOUNT_TYPES
(
  ACCOUNT_TYPE_ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_6A55196D_D1A2_4155_A62D_45E93C62B9DB) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  TYPE VARCHAR(255) NOT NULL
);
CREATE TABLE CITIES
(
  CITY_ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_2256A568_5821_4A85_BD09_B3B513EA222F) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  CITY_NAME VARCHAR(255) NOT NULL
);
CREATE TABLE CLIENTS
(
  CLIENT_ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_80A4D665_CB9A_4E2E_8233_EDC3E5B3C659) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  PHONE VARCHAR(255),
  CITY_ID INTEGER,
  CONSTRAINT CONSTRAINT_5E FOREIGN KEY (CITY_ID) REFERENCES CITIES (CITY_ID)
);