CREATE TABLE ACCOUNTS
(
    ACCOUNT_ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_0ACB6E31_EC45_4118_B5DD_F916F2DA70BC) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CLIENT_ID INTEGER NOT NULL,
    DEPOSIT DOUBLE NOT NULL,
    ACCOUNT_TYPE INTEGER,
    OVERDRAFT INTEGER
);
CREATE TABLE ACCOUNT_TYPES
(
    ACCOUNT_TYPE_ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_0DD64216_EB9B_4FF6_8FF2_CAB0EAFC2EE7) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TYPE VARCHAR(255) not null
);
CREATE TABLE CITIES
(
    CITY_ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_CEA874A3_0B1C_4E5E_8D1A_60B75675F339) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CITY_NAME VARCHAR(255) not null
);
CREATE TABLE CLIENTS
(
    CLIENT_ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_A689859F_EFE8_465A_9321_6FA90268F1C3) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255),
    CITY INTEGER
);