INSERT INTO PUBLIC.CITIES (CITY_NAME) VALUES ('Dnepr');
INSERT INTO PUBLIC.CITIES (CITY_NAME) VALUES ('Kiev');
INSERT INTO PUBLIC.CITIES (CITY_NAME) VALUES ('Lvov');
INSERT INTO PUBLIC.CITIES (CITY_NAME) VALUES ('Odessa');