INSERT INTO PUBLIC.CITIES (CITY_NAME) VALUES ('Dnepr');
INSERT INTO PUBLIC.CITIES (CITY_NAME) VALUES ('Kiev');
INSERT INTO PUBLIC.CITIES (CITY_NAME) VALUES ('Lvov');
INSERT INTO PUBLIC.CITIES (CITY_NAME) VALUES ('Odessa');
INSERT INTO PUBLIC.CITIES (CITY_NAME) VALUES ('City');
INSERT INTO PUBLIC.CITIES (CITY_NAME) VALUES ('Springfield');
INSERT INTO PUBLIC.CITIES (CITY_NAME) VALUES ('SouthPark');